// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JustThingsDbContext))]
    partial class JustThingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Catalogue.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_brands");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_brands_slug");

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("Domain.Catalogue.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("VerticalId")
                        .HasColumnType("uuid")
                        .HasColumnName("vertical_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("VerticalId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_vertical_id_slug");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Domain.Catalogue.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<int>("CoatsRecommended")
                        .HasColumnType("integer")
                        .HasColumnName("coats_recommended");

                    b.Property<decimal>("CoveragePerLitre")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("coverage_per_litre");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsTintable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tintable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<Guid>("VerticalId")
                        .HasColumnType("uuid")
                        .HasColumnName("vertical_id");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("VerticalId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_products_vertical_id_slug");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Domain.Catalogue.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("HazardClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hazard_class");

                    b.Property<int?>("HeightMm")
                        .HasColumnType("integer")
                        .HasColumnName("height_mm");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("LengthMm")
                        .HasColumnType("integer")
                        .HasColumnName("length_mm");

                    b.Property<decimal>("PackLitres")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)")
                        .HasColumnName("pack_litres");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Sheen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sheen");

                    b.Property<decimal>("SheenUpliftFactor")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("sheen_uplift_factor");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("sku");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)")
                        .HasColumnName("weight_kg");

                    b.Property<int?>("WidthMm")
                        .HasColumnType("integer")
                        .HasColumnName("width_mm");

                    b.HasKey("Id")
                        .HasName("pk_product_variants");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_product_variants_sku");

                    b.HasIndex("ProductId", "Sheen", "PackLitres")
                        .IsUnique()
                        .HasDatabaseName("ix_product_variants_product_id_sheen_pack_litres");

                    b.ToTable("product_variants", (string)null);
                });

            modelBuilder.Entity("Domain.Colours.Colour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<Guid>("ColourSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("colour_system_id");

                    b.Property<string>("Hex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("hex");

                    b.Property<string>("HueFamily")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hue_family");

                    b.Property<bool>("IsDiscontinued")
                        .HasColumnType("boolean")
                        .HasColumnName("is_discontinued");

                    b.Property<decimal?>("Lrv")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("lrv");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_colours");

                    b.HasIndex("HueFamily")
                        .HasDatabaseName("ix_colours_hue_family");

                    b.HasIndex("ColourSystemId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_colours_colour_system_id_code");

                    b.ToTable("colours", (string)null);
                });

            modelBuilder.Entity("Domain.Colours.ColourAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ColourId")
                        .HasColumnType("uuid")
                        .HasColumnName("colour_id");

                    b.Property<decimal>("ColourantSurchargeExVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("colourant_surcharge_ex_vat");

                    b.Property<bool>("IsDiscontinued")
                        .HasColumnType("boolean")
                        .HasColumnName("is_discontinued");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("TintBaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("tint_base_id");

                    b.HasKey("Id")
                        .HasName("pk_colour_availabilities");

                    b.HasIndex("ColourId")
                        .HasDatabaseName("ix_colour_availabilities_colour_id");

                    b.HasIndex("TintBaseId")
                        .HasDatabaseName("ix_colour_availabilities_tint_base_id");

                    b.HasIndex("ProductId", "ColourId")
                        .IsUnique()
                        .HasDatabaseName("ix_colour_availabilities_product_id_colour_id");

                    b.ToTable("colour_availabilities", (string)null);
                });

            modelBuilder.Entity("Domain.Colours.ColourSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsProprietary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_proprietary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerSellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_seller_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_colour_systems");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_colour_systems_slug");

                    b.ToTable("colour_systems", (string)null);
                });

            modelBuilder.Entity("Domain.Colours.TintBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<decimal>("UpliftPerLitreExVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("uplift_per_litre_ex_vat");

                    b.HasKey("Id")
                        .HasName("pk_tint_bases");

                    b.HasIndex("SellerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tint_bases_seller_id_name");

                    b.ToTable("tint_bases", (string)null);
                });

            modelBuilder.Entity("Domain.Ordering.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnonymousId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("anonymous_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VerticalId")
                        .HasColumnType("uuid")
                        .HasColumnName("vertical_id");

                    b.HasKey("Id")
                        .HasName("pk_carts");

                    b.HasIndex("AnonymousId")
                        .HasDatabaseName("ix_carts_anonymous_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_carts_customer_id");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("Domain.Ordering.CartLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid")
                        .HasColumnName("cart_id");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_cart_lines");

                    b.HasIndex("CartId")
                        .HasDatabaseName("ix_cart_lines_cart_id");

                    b.HasIndex("OfferId")
                        .HasDatabaseName("ix_cart_lines_offer_id");

                    b.ToTable("cart_lines", (string)null);
                });

            modelBuilder.Entity("Domain.Ordering.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_at");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("reference_number");

                    b.Property<decimal>("ShippingIncVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("shipping_inc_vat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal>("SubtotalIncVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal_inc_vat");

                    b.Property<decimal>("TotalIncVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_inc_vat");

                    b.Property<decimal>("VatFraction")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("vat_fraction");

                    b.Property<Guid>("VerticalId")
                        .HasColumnType("uuid")
                        .HasColumnName("vertical_id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_reference_number");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Domain.Ordering.OrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<decimal>("PackLitres")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)")
                        .HasColumnName("pack_litres");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Returnability")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("returnability");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("SheenName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sheen_name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("sku");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_order_lines");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_lines_order_id");

                    b.ToTable("order_lines", (string)null);
                });

            modelBuilder.Entity("Domain.Pricing.PricingTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("multiplier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_pricing_tiers");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_pricing_tiers_name");

                    b.ToTable("pricing_tiers", (string)null);
                });

            modelBuilder.Entity("Domain.Sellers.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FulfilmentMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("fulfilment_mode");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("integer")
                        .HasColumnName("lead_time_days");

                    b.Property<decimal>("PriceExVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_ex_vat");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("stock_quantity");

                    b.HasKey("Id")
                        .HasName("pk_offers");

                    b.HasIndex("ProductVariantId")
                        .HasDatabaseName("ix_offers_product_variant_id");

                    b.HasIndex("SellerId", "ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("ix_offers_seller_id_product_variant_id");

                    b.ToTable("offers", (string)null);
                });

            modelBuilder.Entity("Domain.Sellers.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("commission_rate");

                    b.Property<string>("CompanyRegistrationNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("company_registration_number");

                    b.Property<string>("DefaultFulfilmentMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("default_fulfilment_mode");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("vat_number");

                    b.HasKey("Id")
                        .HasName("pk_sellers");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_sellers_slug");

                    b.ToTable("sellers", (string)null);
                });

            modelBuilder.Entity("Domain.Verticals.Vertical", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("hostname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_verticals");

                    b.HasIndex("Hostname")
                        .IsUnique()
                        .HasDatabaseName("ix_verticals_hostname");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_verticals_slug");

                    b.ToTable("verticals", (string)null);
                });

            modelBuilder.Entity("Domain.Catalogue.ProductVariant", b =>
                {
                    b.HasOne("Domain.Catalogue.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_variants_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Colours.Colour", b =>
                {
                    b.HasOne("Domain.Colours.ColourSystem", "ColourSystem")
                        .WithMany("Colours")
                        .HasForeignKey("ColourSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_colours_colour_systems_colour_system_id");

                    b.Navigation("ColourSystem");
                });

            modelBuilder.Entity("Domain.Colours.ColourAvailability", b =>
                {
                    b.HasOne("Domain.Colours.Colour", "Colour")
                        .WithMany()
                        .HasForeignKey("ColourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_colour_availabilities_colours_colour_id");

                    b.HasOne("Domain.Colours.TintBase", "TintBase")
                        .WithMany()
                        .HasForeignKey("TintBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_colour_availabilities_tint_bases_tint_base_id");

                    b.Navigation("Colour");

                    b.Navigation("TintBase");
                });

            modelBuilder.Entity("Domain.Ordering.CartLine", b =>
                {
                    b.HasOne("Domain.Ordering.Cart", null)
                        .WithMany("Lines")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_lines_carts_cart_id");

                    b.HasOne("Domain.Sellers.Offer", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cart_lines_offers_offer_id");

                    b.OwnsOne("Domain.Ordering.LineConfiguration", "Configuration", b1 =>
                        {
                            b1.Property<Guid>("CartLineId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ColourCode")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("configuration_colour_code");

                            b1.Property<string>("ColourHex")
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("configuration_colour_hex");

                            b1.Property<Guid?>("ColourId")
                                .HasColumnType("uuid")
                                .HasColumnName("configuration_colour_id");

                            b1.Property<string>("ColourName")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("configuration_colour_name");

                            b1.Property<bool>("IsMadeToOrder")
                                .HasColumnType("boolean")
                                .HasColumnName("configuration_is_made_to_order");

                            b1.Property<decimal>("ResolvedPriceExVat")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("configuration_resolved_price_ex_vat");

                            b1.Property<decimal>("ResolvedPriceIncVat")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("configuration_resolved_price_inc_vat");

                            b1.Property<Guid?>("TintBaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("configuration_tint_base_id");

                            b1.Property<string>("TintBaseName")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("configuration_tint_base_name");

                            b1.Property<decimal>("VatFraction")
                                .HasPrecision(6, 4)
                                .HasColumnType("numeric(6,4)")
                                .HasColumnName("configuration_vat_fraction");

                            b1.HasKey("CartLineId");

                            b1.ToTable("cart_lines");

                            b1.WithOwner()
                                .HasForeignKey("CartLineId")
                                .HasConstraintName("fk_cart_lines_cart_lines_id");
                        });

                    b.Navigation("Configuration")
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Domain.Ordering.OrderLine", b =>
                {
                    b.HasOne("Domain.Ordering.Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_lines_orders_order_id");

                    b.OwnsOne("Domain.Ordering.LineConfiguration", "Configuration", b1 =>
                        {
                            b1.Property<Guid>("OrderLineId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ColourCode")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("configuration_colour_code");

                            b1.Property<string>("ColourHex")
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("configuration_colour_hex");

                            b1.Property<Guid?>("ColourId")
                                .HasColumnType("uuid")
                                .HasColumnName("configuration_colour_id");

                            b1.Property<string>("ColourName")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("configuration_colour_name");

                            b1.Property<bool>("IsMadeToOrder")
                                .HasColumnType("boolean")
                                .HasColumnName("configuration_is_made_to_order");

                            b1.Property<decimal>("ResolvedPriceExVat")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("configuration_resolved_price_ex_vat");

                            b1.Property<decimal>("ResolvedPriceIncVat")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("configuration_resolved_price_inc_vat");

                            b1.Property<Guid?>("TintBaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("configuration_tint_base_id");

                            b1.Property<string>("TintBaseName")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("configuration_tint_base_name");

                            b1.Property<decimal>("VatFraction")
                                .HasPrecision(6, 4)
                                .HasColumnType("numeric(6,4)")
                                .HasColumnName("configuration_vat_fraction");

                            b1.HasKey("OrderLineId");

                            b1.ToTable("order_lines");

                            b1.WithOwner()
                                .HasForeignKey("OrderLineId")
                                .HasConstraintName("fk_order_lines_order_lines_id");
                        });

                    b.Navigation("Configuration")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Sellers.Offer", b =>
                {
                    b.HasOne("Domain.Catalogue.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_offers_product_variants_product_variant_id");

                    b.HasOne("Domain.Sellers.Seller", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_offers_sellers_seller_id");

                    b.Navigation("ProductVariant");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Domain.Catalogue.Product", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Domain.Colours.ColourSystem", b =>
                {
                    b.Navigation("Colours");
                });

            modelBuilder.Entity("Domain.Ordering.Cart", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Domain.Ordering.Order", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
